site_name: LangRouter
docs_dir: core/components/langrouter/docs/mkdocs
site_dir: _build/site

repo_url: https://github.com/Jako/LangRouter

pages:
- Home: 'index.md'
- Installation: 'installation.md'
- Usage: 'usage.md'

theme: flatly

markdown_extensions:
    - footnotes
    - tables